In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r'C:\Users\ALL AtoZ\Downloads\archive\data\Transactions.csv')
df.head()

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
0,1-11-2001-165,11,1,مبايعات,Sales,بيع,Sell,24-02-2001,1,أرض,...,NaN,0,1393.55,1350000.0,968.75,NaN,NaN,1.0,1.0,0.0
1,3-9-2004-223,9,3,هبات,Gifts,هبه,Grant,13-12-2004,4,فيلا,...,NaN,0,1728.00,2790000.0,1614.58,NaN,NaN,1.0,1.0,0.0
2,2-13-1996-119,13,2,رهون,Mortgages,تسجيل رهن,Mortgage Registration,12-03-2001,1,أرض,...,NaN,0,929.03,20000000.0,21527.83,NaN,NaN,1.0,1.0,0.0
3,2-14-2005-222,14,2,رهون,Mortgages,تعديل رهن,Modify Mortgage,20-09-2005,2,مبنى,...,NaN,0,2673.28,25000000.0,9351.81,NaN,NaN,1.0,1.0,0.0
4,3-9-2012-874,9,3,هبات,Gifts,هبه,Grant,11-10-2012,4,فيلا,...,NaN,0,1541.17,9000000.0,5839.72,NaN,NaN,1.0,1.0,0.0

In [4]:
df.columns

Index(['transaction_id', 'procedure_id', 'trans_group_id', 'trans_group_ar',
       'trans_group_en', 'procedure_name_ar', 'procedure_name_en',
       'instance_date', 'property_type_id', 'property_type_ar',
       'property_type_en', 'property_sub_type_id', 'property_sub_type_ar',
       'property_sub_type_en', 'property_usage_ar', 'property_usage_en',
       'reg_type_id', 'reg_type_ar', 'reg_type_en', 'area_id', 'area_name_ar',
       'area_name_en', 'building_name_ar', 'building_name_en',
       'project_number', 'project_name_ar', 'project_name_en',
       'master_project_en', 'master_project_ar', 'nearest_landmark_ar',
       'nearest_landmark_en', 'nearest_metro_ar', 'nearest_metro_en',
       'nearest_mall_ar', 'nearest_mall_en', 'rooms_ar', 'rooms_en',
       'has_parking', 'procedure_area', 'actual_worth', 'meter_sale_price',
       'rent_value', 'meter_rent_price', 'no_of_parties_role_1',
       'no_of_parties_role_2', 'no_of_parties_role_3'],
      dtype='object')

In [6]:
df.isnull().sum()

transaction_id                0
procedure_id                  0
trans_group_id                0
trans_group_ar                0
trans_group_en                0
procedure_name_ar             0
procedure_name_en             0
instance_date                 5
property_type_id              0
property_type_ar              0
property_type_en              0
property_sub_type_id     240146
property_sub_type_ar     240146
property_sub_type_en     240146
property_usage_ar             0
property_usage_en             0
reg_type_id                   0
reg_type_ar                   0
reg_type_en                   0
area_id                       0
area_name_ar                  0
area_name_en                  0
building_name_ar         328165
building_name_en         326895
project_number           390593
project_name_ar          390593
project_name_en          390593
master_project_en        183812
master_project_ar        183859
nearest_landmark_ar      125724
nearest_landmark_en      125724
nearest_metro_ar         236824
nearest_metro_en         236824
nearest_mall_ar          242142
nearest_mall_en          242142
rooms_ar                 248935
rooms_en                 248935
has_parking                   0
procedure_area                0
actual_worth               3805
meter_sale_price              0
rent_value              1013666
meter_rent_price        1013663
no_of_parties_role_1       1152
no_of_parties_role_2       1152
no_of_parties_role_3       1152
dtype: int64

In [8]:
df.shape

(1047965, 46)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1047965 entries, 0 to 1047964
Data columns (total 46 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   transaction_id        1047965 non-null  object
 1   procedure_id          1047965 non-null  int64
 2   trans_group_id        1047965 non-null  int64
 3   trans_group_ar        1047965 non-null  object
 4   trans_group_en        1047965 non-null  object
 5   procedure_name_ar     1047965 non-null  object
 6   procedure_name_en     1047965 non-null  object
 7   instance_date         1047960 non-null  object
 8   property_type_id      1047965 non-null  int64
 9   property_type_ar      1047965 non-null  object
 10  property_type_en      1047965 non-null  object
 11  property_sub_type_id  807819 non-null   float64
 12  property_sub_type_ar  807819 non-null   object
 13  property_sub_type_en  807819 non-null   object
 14  property_usage_ar     1047965 non-null  object
 15  property_usage_en     1047965 non-null  object
 16  reg_type_id           1047965 non-null  int64
 17  reg_type_ar           1047965 non-null  object
 18  reg_type_en           1047965 non-null  object
 19  area_id               1047965 non-null  int64
 20  area_name_ar          1047965 non-null  object
 21  area_name_en          1047965 non-null  object
 22  building_name_ar      719800 non-null   object
 23  building_name_en      721070 non-null   object
 24  project_number        657372 non-null   float64
 25  project_name_ar       657372 non-null   object
 26  project_name_en       657372 non-null   object
 27  master_project_en     864153 non-null   object
 28  master_project_ar     864106 non-null   object
 29  nearest_landmark_ar   922241 non-null   object
 30  nearest_landmark_en   922241 non-null   object
 31  nearest_metro_ar      811141 non-null   object
 32  nearest_metro_en      811141 non-null   object
 33  nearest_mall_ar       805823 non-null   object
 34  nearest_mall_en       805823 non-null   object
 35  rooms_ar              799030 non-null   object
 36  rooms_en              799030 non-null   object
 37  has_parking           1047965 non-null  int64
 38  procedure_area        1047965 non-null  float64
 39  actual_worth          1044160 non-null  float64
 40  meter_sale_price      1047965 non-null  float64
 41  rent_value            34299 non-null    float64
 42  meter_rent_price      34302 non-null    float64
 43  no_of_parties_role_1  1046813 non-null  float64
 44  no_of_parties_role_2  1046813 non-null  float64
 45  no_of_parties_role_3  1046813 non-null  float64
dtypes: float64(10), int64(6), object(30)
memory usage: 367.8+ MB

In [11]:
df.describe()

,procedure_id,trans_group_id,property_type_id,property_sub_type_id,reg_type_id,area_id,project_number,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
count,1.047965e+06,1.047965e+06,1.047965e+06,807819.000000,1.047965e+06,1.047965e+06,657372.000000,1.047965e+06,1.047965e+06,1.044160e+06,1.047965e+06,3.429900e+04,3.430200e+04,1.046813e+06,1.046813e+06,1.046813e+06
mean,5.870308e+01,1.282417e+00,3.022047e+00,53.897052,7.054300e-01,4.083695e+02,1281.808831,5.983988e-01,1.599632e+03,2.557483e+06,1.348875e+04,1.416090e+06,2.102467e+04,1.285542e+00,1.193500e+00,1.559524e-01
std,9.111008e+01,5.207231e-01,7.345969e-01,20.642155,4.558494e-01,7.036101e+01,703.100973,4.902223e-01,3.558513e+05,5.968448e+06,1.246936e+05,1.733329e+06,2.934084e+05,3.301961e+00,5.187964e-01,6.239861e-01
min,4.000000e+00,1.000000e+00,1.000000e+00,2.000000,0.000000e+00,2.290000e+02,-2480.000000,0.000000e+00,5.000000e-02,1.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.100000e+01,1.000000e+00,3.000000e+00,60.000000,0.000000e+00,3.500000e+02,615.000000,0.000000e+00,7.228000e+01,6.804000e+05,6.210910e+03,5.984930e+05,4.940000e+03,1.000000e+00,1.000000e+00,0.000000e+00
50%,1.300000e+01,1.000000e+00,3.000000e+00,60.000000,1.000000e+00,4.120000e+02,1387.000000,1.000000e+00,1.224700e+02,1.245500e+06,9.334010e+03,1.001000e+06,7.152500e+03,1.000000e+00,1.000000e+00,0.000000e+00
75%,1.020000e+02,1.000000e+00,3.000000e+00,60.000000,1.000000e+00,4.620000e+02,1821.000000,1.000000e+00,2.555700e+02,2.285490e+06,1.404738e+04,1.760000e+06,1.007075e+04,1.000000e+00,1.000000e+00,0.000000e+00
max,8.610000e+02,3.000000e+00,4.000000e+00,112.000000,1.000000e+00,5.310000e+02,2602.000000,1.000000e+00,3.421034e+08,9.997125e+07,3.499578e+07,8.500000e+07,1.109416e+07,7.030000e+02,5.100000e+01,1.700000e+01